//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogTrackerApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpInfo()
        {
            this.BlogInfoes = new HashSet<BlogInfo>();
        }
    
        public string EmailId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<int> PassCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogInfo> BlogInfoes { get; set; }
    }
}
